/* Catálogo independiente: no altera la carga de libros ni los favoritos. */
(()=>{'use strict';
const target=document.getElementById('apps-catalog'), status=document.getElementById('apps-status');
const initial=[{categoria:'Aprendizaje-Servicio',nombre:'Aprendizaje y Servicio Solidario',url:'https://aprendizajeserviciosolidario.netlify.app/',imagen:'',descripcion:'',orden:1,visible:true},{categoria:'Aprendizaje-Servicio',nombre:'Guías de Aprendizaje-Servicio',url:'https://guiasaps.netlify.app/',imagen:'',descripcion:'',orden:2,visible:true}];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function validUrl(value){try{let u=new URL(value);return u.protocol==='https:'||u.protocol==='http:'?u.href:null}catch{return null}}
let catalog=initial;function draw(items){catalog=items;target.replaceChildren();const groups=new Map();items.filter(x=>x.visible!==false&&String(x.visible).toLowerCase()!=='no'&&String(x.visible).toLowerCase()!=='false').sort((a,b)=>(Number(a.orden)||999)-(Number(b.orden)||999)).forEach(x=>{if(!validUrl(x.url))return;const cat=String(x.categoria||'Otros aplicativos').trim();if(!groups.has(cat))groups.set(cat,[]);groups.get(cat).push(x)});const selected=document.getElementById('folder').value;for(const [cat,entries] of groups){if(selected && selected!==('app:'+cat))continue;const heading=document.createElement('div');heading.className='section';const h=document.createElement('h2');h.textContent='📚 '+cat;heading.append(h);target.append(heading);const shelf=document.createElement('section');shelf.className='shelf';shelf.setAttribute('aria-label','Aplicativos de '+cat);for(const app of entries){const a=document.createElement('a');a.className='app-tile';a.href=validUrl(app.url);a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label','Abrir '+app.nombre+' en otra pestaña');const image=validUrl(app.imagen);if(image){const img=document.createElement('img');img.src=image;img.alt='';img.loading='lazy';img.onerror=()=>{img.replaceWith(makeEmoji())};a.append(img)}else a.append(makeEmoji());const title=document.createElement('span');title.className='app-label';title.textContent=app.nombre||'Aplicativo';a.append(title);if(app.descripcion){const desc=document.createElement('span');desc.className='app-description';desc.textContent=app.descripcion;a.append(desc)}const arrow=document.createElement('span');arrow.className='app-arrow';arrow.textContent='↗';a.append(arrow);shelf.append(a)}target.append(shelf)}}
function updateAppOptions(){const select=document.getElementById('folder');const previous=select.value;select.querySelectorAll('option[data-app]').forEach(x=>x.remove());const cats=[...new Set(catalog.filter(x=>x.visible!==false&&String(x.visible).toLowerCase()!=='no'&&String(x.visible).toLowerCase()!=='false'&&validUrl(x.url)).map(x=>String(x.categoria||'Otros aplicativos').trim()))].filter(x=>x.toLocaleLowerCase('es')!=='general').sort((a,b)=>a.localeCompare(b,'es'));for(const cat of cats){const o=document.createElement('option');o.value='app:'+cat;o.textContent='📱 '+cat;o.dataset.app='1';select.append(o)}if([...select.options].some(x=>x.value===previous))select.value=previous;draw(catalog)}document.getElementById('folder').addEventListener('change',()=>draw(catalog));document.addEventListener('biblioteca:folders-updated',updateAppOptions);function makeEmoji(){const span=document.createElement('span');span.className='app-emoji';span.textContent='📱';return span}
const api=String(window.BIBLIOTECA_APPS_API_URL||'').trim();if(!api){updateAppOptions();return}
const callback='unirAppsCallback';const script=document.createElement('script');let done=false;const timer=setTimeout(()=>fail('El catálogo de aplicativos tardó demasiado en responder.'),15000);
function fail(message){if(done)return;done=true;clearTimeout(timer);script.remove();delete window[callback];status.textContent=message+' Se muestran los accesos de respaldo.';updateAppOptions()}
window[callback]=data=>{if(done)return;if(!data||data.ok!==true||!Array.isArray(data.apps)){fail(data&&data.error?'Error del catálogo: '+data.error:'Respuesta inválida del catálogo.');return}done=true;clearTimeout(timer);script.remove();delete window[callback];status.textContent='';catalog=data.apps;updateAppOptions()};
script.onerror=()=>fail('No se pudo conectar al administrador de aplicativos.');script.src=api+(api.includes('?')?'&':'?')+'callback='+callback+'&t='+Date.now();document.head.append(script);
})();
